theme: jekyll-theme-hacker
header: none
header_pages:
  - README.md
  - Work.md
title: Jahanvi Patel
github:
  is_project_page: false
  
owner:
  name: Jahanvi Patel
  avatar: 1_circle.png
  bio: "Sample Bio"
  email: jahanvi316@gmail.com
  linkedin: #jahanvipatel
  github: jahanvi316
