theme: jekyll-theme-hacker
icon: "favicon.ico"
navbar-links:
  Home: README.md
  Projects: Work.md
title: Jahanvi Patel
github:
  is_project_page: false
author: Jahanvi Patel
owner:
  name: Jahanvi Patel
  avatar: 1_circle.png
  bio: "Sample Bio"
  email: jahanvi316@gmail.com
  linkedin: #jahanvipatel
  github: jahanvi316
